# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  host: localhost
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: postgres
  password:
  timeout: 5000

development:
  <<: *default
  database: aircall_development

test:
  <<: *default
  database: aircall_test

production:
  <<: *default
  host: <%= ENV["PG_HOST"] %>
  port: <%= ENV["PG_PORT"] || 5432 %>
  username: <%= ENV["PG_USER"] %>
  password: <%= ENV["PG_PASSWORD"] %>
  database: <%= ENV["PG_DATABASE"] %>
  pool: <%= ENV["DB_POOL"] || ENV["MAX_THREADS"] || 5 %>
